module.exports = (grunt) ->	

	# Local paths
	comp = 'web/components/'
	css = 'web/css/'
	sass = 'web/sass/'
	js = 'web/js/'
	img = 'web/img/'
	font = 'web/font/'
	coffee = 'web/coffee/'
	dart = 'web/dart/'
	dist = 'dist/'
	build = 'build/'

	# Remote paths
	cdnUrl = '//s3.amazonaws.com/static.tok3n.com/<%= pkg.version %>/'
		
	# Regex
	css_file = /([^\/]+)\.css$/

	@initConfig
		
		# Versions, names for licenses
		pkg: grunt.file.readJSON 'package.json'
		aws: grunt.file.readJSON '/Users/aficio/Dropbox/Development/Amazon/tok3n-aficio.json'

		shell:
			sleep:
				command: 'sleep 3s'

		curl:
			index:
				dest: dist + 'index.html'
				src: 'http://localhost:5000'
			apps:
				dest: dist + 'apps.html'
				src: 'http://localhost:5000/apps'
			loginV2:
				dest: dist + 'login-v2.html'
				src: 'http://localhost:5000/login-v2'
			masonry:
				dest: js + 'masonry.pkgd.min.js'
				src: 'http://masonry.desandro.com/masonry.pkgd.min.js'
			buoy:
				dest: js + 'buoy.js'
				src: 'https://raw.githubusercontent.com/cferdinandi/buoy/master/buoy.js'
		
		copy:
			jquery:
				src: comp + 'jquery/jquery.js'
				dest: js + 'jquery.js'

		coffee: 
			options:
				bare: true
			main:
				src: coffee + 'main.coffee'
				dest: js + 'main.js'
			test:
				src: coffee + 'test.coffee'
				dest: js + 'test.js'
			connect:
				src: coffee + 'connect.coffee'
				dest: js + 'connect.js'
		
		compass:
			options:
				outputStyle: 'expanded'
				raw: 'preferred_syntax = :sass\n::Sass::Script::Number.precision = [10, ::Sass::Script::Number.precision].max\n
					sass_options = {:quiet => true}\n'
				require: ['breakpoint-slicer', 'animate']
				cssDir: css
				sassDir: sass
				imagesDir: img
				fontsDir: font
				javascriptsDir: js
			dev:
				options:
					relativeAssets: true
					force: true
			watch:
				options:
					relativeAssets: true
			production:
				options:
					force: true
					relativeAssets: false
					httpPath: cdnUrl
					httpJavascriptsPath: cdnUrl + 'js'
					httpStylesheetsPath: cdnUrl + 'css'
					httpImagesPath: cdnUrl + 'img'
					httpFontsPath: cdnUrl + 'font'
		
		csslint:
			options:
				csslintrc: '.csslintrc'
			files:
				src: [
					css + 'base.css'
					css + 'main.css'
				]
				
		concat:
			options:
				separator: '\n'
			dashboard:
				src: [
					js + 'masonry.pkgd.min.js'
					js + 'modernizr.js'
					'<%= coffee.main.dest %>'
				]
				dest: js + 'dashboard.js'
			connect:
				src: [
					comp + 'ladda/js/spin.js'
					comp + 'ladda/js/ladda.js'
					'<%= coffee.connect.dest %>'
				]
				dest: js + 'connect.js'

		uglify:
			options:
				mangle: true
				compress: true
				report: 'gzip'
				preserveComments: 'some'
				banner: [
					'/*!'
					' * <%= pkg.name %> v<%= pkg.version %> - <%= grunt.template.today("yyyy-mm-dd") %>'
					' * <%= pkg.description %>'
					' * Automatically generated by Grunt.js'
					' */\n'
				].join '\n'
			dashboard:
				src: '<%= concat.dashboard.dest %>'
				dest: js + 'dashboard-min.js'
			connect:
				src: '<%= concat.connect.dest %>'
				dest: js + 'connect-min.js'
		
		replace:
			dist:
				src: dist + '*.html'
				overwrite: true
				replacements: [
					{
						from: /(['"])css\/([^\/\n"']*)\.css(['"])/g
						to: '$1' + cdnUrl + 'css/$2-min.css$3'
					}
					{
						from: "url('../img/"
						to: "url('" + cdnUrl + "img/"
					}
					{
						from: "url('../fonts/"
						to: "url('" + cdnUrl + "fonts/"
					}
					{
						from: "url('fonts/"
						to: "url('" + cdnUrl + "fonts/"
					}
				]
			# Sometimes compass does not compile correctly with the change to absolute refs, this is a hackish and temporal solution
			css:
				src: dist + 'css/style.css'
				overwrite: true
				replacements: [
					{
						from: '../img/'
						to: cdnUrl + 'img/'
					}
				]
			dashboard:
				src: '<%= uglify.dashboard.dest %>'
				dest: dist + 'js/dashboard-min.js'
				replacements: [
					from: ',/*!'
					to: ',\n/*!'
				]

		processhtml:
			options:
				data:
					cdnUrl: cdnUrl
				process: true
			index:
				src: dist + 'index.html'
				dest: dist + 'index.html'
			apps:
				src: dist + 'apps.html'
				dest: dist + 'apps.html'
			loginV2:
				src: dist + 'login-v2.html'
				dest: dist + 'login-v2.html'

		prettify:
			html:
				options:
					unformatted: ['a', 'sub', 'sup', 'b', 'i', 'u', 'script']
				expand: true
				cwd: dist
				ext: '.html'
				src: ['*.html']
				dest: dist

		cssmin:
			dist:
				options:
					report: 'gzip'
					banner: [
						'/*!'
						' *  TTTTTTTTTTTTTTTTTTTTTTT              kkkkkkkk           333333333333333'
						' *  T:::::::::::::::::::::T              k::::::k          3:::::::::::::::33'
						' *  T:::::::::::::::::::::T              k::::::k          3::::::33333::::::3'
						' *  T:::::TT:::::::TT:::::T              k::::::k          3333333     3:::::3'
						' *  TTTTTT  T:::::T  TTTTTTooooooooooo    k:::::k    kkkkkkk           3:::::3nnnn  nnnnnnnn'
						' *          T:::::T      oo:::::::::::oo  k:::::k   k:::::k            3:::::3n:::nn::::::::nn'
						' *          T:::::T     o:::::::::::::::o k:::::k  k:::::k     33333333:::::3 n::::::::::::::nn'
						' *          T:::::T     o:::::ooooo:::::o k:::::k k:::::k      3:::::::::::3  nn:::::::::::::::n'
						' *          T:::::T     o::::o     o::::o k::::::k:::::k       33333333:::::3   n:::::nnnn:::::n'
						' *          T:::::T     o::::o     o::::o k:::::::::::k                3:::::3  n::::n    n::::n'
						' *          T:::::T     o::::o     o::::o k:::::::::::k                3:::::3  n::::n    n::::n'
						' *          T:::::T     o::::o     o::::o k::::::k:::::k               3:::::3  n::::n    n::::n'
						' *        TT:::::::TT   o:::::ooooo:::::ok::::::k k:::::k  3333333     3:::::3  n::::n    n::::n'
						' *        T:::::::::T   o:::::::::::::::ok::::::k  k:::::k 3::::::33333::::::3  n::::n    n::::n'
						' *        T:::::::::T    oo:::::::::::oo k::::::k   k:::::k3:::::::::::::::33   n::::n    n::::n'
						' *        TTTTTTTTTTT      ooooooooooo   kkkkkkkk    kkkkkkk333333333333333     nnnnnn    nnnnnn'
						' *'
						' * <%= pkg.name %> v<%= pkg.version %> - <%= grunt.template.today("yyyy-mm-dd") %>'
						' * <%= pkg.description %>'
						' * Copyright <%= grunt.template.today("yyyy") %> Token Soluciones Tecnologicas, SAPI de CV. All rights reserved.'
						' * Licensed under the MIT License'
						' * https://github.com/Tok3n/tok3n-webapp/blob/master/LICENSE'
						' *'
						' * Thanks for stopping by!'
						' * please refer to the full SASS in (../sass/<filename>.sass) for complete code.'
						' *'
						' */'
					].join '\n'
				files: [
					{
						expand: true
						replace: true
						cwd: css
						src: ['*.css', '!*-min.css']
						dest: css
						ext: '-min.css'
					}
				]

		sync:
			dist:
				files:[
					{
						cwd: 'web'
						src: ['css/*-min.css', 'css/fonts/**', 'sass/**', 'js/*-min.js', 'svg/**', 'img/*.svg']
						dest: dist
					}
				]
			dart:
				files: [
					{
						cwd: 'build/web'
						src: ['dart/**']
						dest: dist
					}
				]

		imagemin:
			dist:
				options:
					optimizationLevel: 3
				files: [
					{
						expand: true
						cwd: img
						src: '{,*/}*.{png,jpg,jpeg}'
						dest: dist + 'img'
					}
				]

		watch:
			options:
				livereload: true
				files: [
					css
					'<%= concat.dashboard.dest %>'
				]
			coffee:
				files: coffee + '*'
				tasks: ['coffee', 'concat']
			sass:
				files: sass + '*'
				tasks: ['compass:watch']
				# tasks: ['compass:watch', 'csslint']

		's3-sync':
			options:
				key: '<%= aws.key %>'
				secret: '<%= aws.secret %>'
				bucket: 'static.tok3n.com'
				db: ->
					levelup = require 'levelup'
					levelup './s3cachedb'
			dist:
				files: [
					{
						root: dist
						src: [dist + 'css/**', dist + 'js/**', dist + 'img/**', dist + 'svg/**', dist + '*.html', dist + 'sass/**', dist + 'dart/**']
						dest: '/<%= pkg.version %>/'
					}
				]
	
	@registerTask 'bower-install', 'Installs Bower dependencies.', ->
		bower = require 'bower'
		done = this.async()
		bower.commands.install()
			.on 'data', (data) ->
				grunt.log.write data
				return
			.on 'end', done
		return


	@loadNpmTasks 'grunt-contrib-concat'
	@loadNpmTasks 'grunt-contrib-compass'
	@loadNpmTasks 'grunt-contrib-csslint'
	@loadNpmTasks 'grunt-contrib-copy'
	@loadNpmTasks 'grunt-contrib-uglify'
	@loadNpmTasks 'grunt-contrib-watch'
	@loadNpmTasks 'grunt-contrib-cssmin'
	@loadNpmTasks 'grunt-contrib-imagemin'
	@loadNpmTasks 'grunt-coffee-redux'
	@loadNpmTasks 'grunt-contrib-coffee'
	@loadNpmTasks 'grunt-shell'
	@loadNpmTasks 'grunt-text-replace'
	@loadNpmTasks 'grunt-s3-sync'
	@loadNpmTasks 'grunt-sync'
	@loadNpmTasks 'grunt-prettify'
	@loadNpmTasks 'grunt-uncss'
	@loadNpmTasks 'grunt-processhtml'
	@loadNpmTasks 'grunt-curl'

	@registerTask 'build', ['bower-install', 'shell:sleep', 'shell:files', 'copy']
	@registerTask 'curlAll', ['curl:index', 'curl:apps', 'curl:loginV2']
	@registerTask 'distBuildHtml', ['sync', 'shell:sleep', 'curlAll', 'replace:dist', 'prettify', 'processhtml']

	@registerTask 'default', ['compass:dev', 'csslint', 'coffee', 'concat']
	@registerTask 'dist', ['compass:production', 'csslint', 'coffee', 'concat', 'uglify', 'cssmin:dist', 'distBuildHtml', 'imagemin:dist', 's3-sync']
